### ISSUE TITLE
Ensure master talons are the ones with the encoders

### ISSUE THREAD

**Issue by kylecorry31** [Gongoliers/Robot2019#10]
Ensure that the CAN ID of the master talons on each side correlates to the talons which have the encoder wire plugged into them. 

https://github.com/Gongoliers/Robot2019/blob/bd403e3d7b6a6bab4f14aaf2208fbee49d8fe02a/src/main/java/frc/robot/subsystems/Drivetrain.java#L44

**Comment by NicholasBottone** [comment]
Confirmed to be accurate
