### ISSUE TITLE
Find trajectory ticks to feet value

### ISSUE THREAD

**Issue by kylecorry31** [Gongoliers/Robot2019#12]
This is the number of encoder ticks per foot of forward motion. This number can be calculated mathematically using the ticks per revolution (4096 I believe) times the gear ratio times the diameter of the wheel in feet times pi. 

https://github.com/Gongoliers/Robot2019/blob/bd403e3d7b6a6bab4f14aaf2208fbee49d8fe02a/src/main/java/frc/robot/subsystems/Drivetrain.java#L265

**Comment by NicholasBottone** [comment]
**Gear Ratio:** 50:24
**Diameter of Middle Wheel in Feet:** 0.5 ft
4096 * (50/24) * 0.5 * π = 13404.1287

**Comment by NicholasBottone** [comment]
Implemented in 21080c16024f54390a9adb3858786b8adb1fd13e
