### ISSUE TITLE
Display CargoManipulator status

### ISSUE THREAD

**Issue by kylecorry31** [Gongoliers/Robot2019#13]
Display the angle of the manipulator, status of the pistons, has cargo, and the direction the intake/outtake wheels are spinning (positive or negative). 

https://github.com/Gongoliers/Robot2019/blob/bd403e3d7b6a6bab4f14aaf2208fbee49d8fe02a/src/main/java/frc/robot/subsystems/CargoManipulator.java#L85

**Comment by NicholasBottone** [comment]
Implemented in #a23b0ad
