### ISSUE TITLE
Control wrist angle rather than speed

### ISSUE THREAD

**Issue by kylecorry31** [Gongoliers/Robot2019#14]
Controlling the wrist speed may be dangerous because the driver could accidentally make it go out of bounds. Instead, control the angle of the wrist by creating a command where the setpoint is determined by the joystick position (Math.abs(joystick.getY()) * Robot.cargoManipulator.MAXIMUM_ANGLE). See https://github.com/Gongoliers/Robot2016/blob/master/Robot2016/src/org/usfirst/frc5112/Robot2016/commands/OperateObstacleArm.java for an actual implementation of this.

https://github.com/Gongoliers/Robot2019/blob/bd403e3d7b6a6bab4f14aaf2208fbee49d8fe02a/src/main/java/frc/robot/subsystems/CargoManipulator.java#L184

**Comment by NicholasBottone** [comment]
Was found to have never been a real bug in the first place, but added clarifying enhancement was added in e4f94acac01ec40b7fbc489a6b1f1d2d5a42d729
