### ISSUE TITLE
Organize commands by subsystem/mode

### ISSUE THREAD

**Issue by kylecorry31** [Gongoliers/Robot2019#15]
There are a lot of commands and it can be hard to find the ones we are looking for. Putting them into packages based on what subsystem they require (or for complex tasks, they can be organized separately like sandstorm). The stuff about aligning to the target can fall under a vision package. Miscellaneous stuff like stop everything and vibration commands can be left under the commands package.

structure
-> commands
    -> sandstorm
    -> drivetrain
    -> cargo
    -> hatch
    -> hab
    -> vision

**Comment by NicholasBottone** [comment]
How do you refactor packages in VSCode? Whenever I refactor it doesn't update the classes and I have to edit the package statements manually. Is there a way to expedite this process?

**Comment by kylecorry31** [comment]
I'm not completely sure, I couldn't find anything or get it to work myself.

**Comment by NicholasBottone** [comment]
Implemented in ece0280a492181b0ec0de6e990f6c0766b6527a2
