### ISSUE TITLE
Add manual control of the hatchula

### ISSUE THREAD

**Issue by kylecorry31** [Gongoliers/Robot2019#21]
You can either do this with the PID setpoints like the cargo wrist, or you can make the controller set the speed and just make it stop when at the bottom and trying to go down. 

States
-------
1. At bottom, go down -> stop
2. At bottom, go up -> up
3. In between, go up/down -> up/down
4. At top, go down -> down
5. At top, go up -> stop

Give some tolerance to the at bottom and at top, so the motor doesn't burnout.

**Comment by NicholasBottone** [comment]
Implemented in 86e447a199a3d0da68cbfaaf71c7f8d29016a342
