### ISSUE TITLE
Start spinning intake while lowering cargo arm

### ISSUE THREAD

**Issue by kylecorry31** [Gongoliers/Robot2019#24]
This could make it so the cargo is obtained before the arm is fully deployed.

**Comment by NicholasBottone** [comment]
The `IntakeCargo` command (as well as all other cargo commands) requires the `CargoManipulator` subsystem... I would assume that the best way to implement this enhancement would be to add `IntakeCargo` as a parallel command at the beginning of the command group but wouldn't it cancel as soon as another command requiring the subsystem starts?  What should I do to counter this @kylecorry31?

**Comment by NicholasBottone** [comment]
Tried to fix this in 86e447a199a3d0da68cbfaaf71c7f8d29016a342, but further work needs to be done regarding the `requires` statements... the current state probably won't work because of this

**Comment by kylecorry31** [comment]
What if you put spinning the cargo intake at the end again (sequential), and then removed the timeout on BringCargoArmToFloor. This would have a similar effect and not mess with the requires statements.

So it should be:
```
addSequential(new VibrateController(OI.manipulatorController, 0.3F));
addSequential(new MoveCargoIntakeToAngle(CargoManipulator.RESTING_ANGLE));
addSequential(new BringCargoArmToFloor()); // TODO: make BringCargoArmToFloor have no timeout
addSequential(new IntakeCargo());
addSequential(new VibrateStop(OI.manipulatorController));
```

**Comment by kylecorry31** [comment]
It would just have to rotate the intake wrist a bit before moving

**Comment by NicholasBottone** [comment]
Should be all done in commit 86e447a199a3d0da68cbfaaf71c7f8d29016a342
