### ISSUE TITLE
Disable vibration of controllers in disabledInit

### ISSUE THREAD

**Issue by kylecorry31** [Gongoliers/Robot2019#25]
This will prevent the bug where the controller vibrates when a command group has been interrupted. 

https://github.com/Gongoliers/Robot2019/blob/96410a1286108a07d053eb5914b679bcb0c20217/src/main/java/frc/robot/Robot.java#L64

**Comment by NicholasBottone** [comment]
Implemented in 86e447a199a3d0da68cbfaaf71c7f8d29016a342
