### ISSUE TITLE
ManualLowerHatchula end

### ISSUE THREAD

**Issue by kylecorry31** [Gongoliers/Robot2019#26]
The end method should stop the hatchula, in case it is interrupted you want this motor to stop. 

https://github.com/Gongoliers/Robot2019/blob/86e447a199a3d0da68cbfaaf71c7f8d29016a342/src/main/java/frc/robot/commands/hatch/ManualLowerHatchula.java#L33

**Comment by NicholasBottone** [comment]
Implemented in 86e447a199a3d0da68cbfaaf71c7f8d29016a342
