### ISSUE TITLE
Move camera stuff to Vision subsystem

### ISSUE THREAD

**Issue by kylecorry31** [Gongoliers/Robot2019#4]
I think it would be neater to create another subsystem (called Vision or VisualSystem or Cameras) and put all the camera related stuff in that. This could then be required by commands and used in a similar way to the other subsystems, like Robot.cameras.switchToFrontCamera(), etc.

https://github.com/Gongoliers/Robot2019/blob/bd403e3d7b6a6bab4f14aaf2208fbee49d8fe02a/src/main/java/frc/robot/Robot.java#L55

**Comment by NicholasBottone** [comment]
Implemented in 16b67a5dc291975bac8aefa32eef55d5c3cd1c1e
