### ISSUE TITLE
HatchManipulator PID tuning

### ISSUE THREAD

**Issue by kylecorry31** [Gongoliers/Robot2019#6]
The PID of the HatchManipulator needs to be tuned - note: it may need different values if it has a hatch or not. 

https://github.com/Gongoliers/Robot2019/blob/bd403e3d7b6a6bab4f14aaf2208fbee49d8fe02a/src/main/java/frc/robot/subsystems/HatchManipulator.java#L31

**Comment by NicholasBottone** [comment]
Progress was made on this in 96410a1286108a07d053eb5914b679bcb0c20217, but further testing and tuning needs to be done before this issue will be closed

**Comment by kylecorry31** [comment]
It appears an kI term may be needed for this, this intergral term will help it overcome the weight of the hatch. 

Another option may be to set the PID to a different value based on whether it is going up or down.
