### ISSUE TITLE
Display HatchManiplator status

### ISSUE THREAD

**Issue by kylecorry31** [Gongoliers/Robot2019#7]
Display the HatchManiplator's angle and piston status on the SmartDashboard within the periodic method. 

https://github.com/Gongoliers/Robot2019/blob/bd403e3d7b6a6bab4f14aaf2208fbee49d8fe02a/src/main/java/frc/robot/subsystems/HatchManipulator.java#L63

**Comment by NicholasBottone** [comment]
Implemented in #a23b0ad
